In [1]:
import tensorflow as tf
from tensorflow import keras
from keras.datasets import imdb

print("Cargando keras.IMDB")
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)
print("Hecho")

Cargando keras.IMDB
Hecho


In [19]:
# Vectorizar los datos

import numpy as np

def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1
    return results

x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

In [15]:
# Vectorizar las etiquetas
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

In [20]:
print(x_train)
print()
print(x_test)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


In [21]:
print(len(x_train))
print(len(x_train[0]))
print(type(x_train[0][0]))

25000
10000
<class 'numpy.float64'>


In [22]:
print(len(x_test))
print(len(x_test[0]))
print(type(x_test[0][0]))

25000
10000
<class 'numpy.float64'>


In [23]:
print(y_train)
print(len(y_train))
print(type(y_train[0]))

[1. 0. 0. ... 0. 1. 0.]
25000
<class 'numpy.float32'>
